// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gempellm/logistic_parcel_api/v1/logistic_parcel_api.proto

package logistic_parcel_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Parcel with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Parcel) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Foo

	if v, ok := interface{}(m.GetCreated()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ParcelValidationError{
				field:  "Created",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ParcelValidationError is the validation error returned by Parcel.Validate if
// the designated constraints aren't met.
type ParcelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ParcelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ParcelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ParcelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ParcelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ParcelValidationError) ErrorName() string { return "ParcelValidationError" }

// Error satisfies the builtin error interface
func (e ParcelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sParcel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ParcelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ParcelValidationError{}

// Validate checks the field values on DescribeParcelV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeParcelV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetParcelId() <= 0 {
		return DescribeParcelV1RequestValidationError{
			field:  "ParcelId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// DescribeParcelV1RequestValidationError is the validation error returned by
// DescribeParcelV1Request.Validate if the designated constraints aren't met.
type DescribeParcelV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeParcelV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeParcelV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeParcelV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeParcelV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeParcelV1RequestValidationError) ErrorName() string {
	return "DescribeParcelV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeParcelV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeParcelV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeParcelV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeParcelV1RequestValidationError{}

// Validate checks the field values on DescribeParcelV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeParcelV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DescribeParcelV1ResponseValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// DescribeParcelV1ResponseValidationError is the validation error returned by
// DescribeParcelV1Response.Validate if the designated constraints aren't met.
type DescribeParcelV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeParcelV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeParcelV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeParcelV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeParcelV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeParcelV1ResponseValidationError) ErrorName() string {
	return "DescribeParcelV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeParcelV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeParcelV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeParcelV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeParcelV1ResponseValidationError{}
