# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: gempellm/logistic_parcel_api/v1/logistic_parcel_api.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import validate.validate_pb2
import google.api.annotations_pb2
import google.protobuf.timestamp_pb2
import gempellm.logistic_parcel_api.v1.logistic_parcel_api_pb2


class LogisticParcelApiServiceBase(abc.ABC):

    @abc.abstractmethod
    async def DescribeParcelV1(self, stream: 'grpclib.server.Stream[gempellm.logistic_parcel_api.v1.logistic_parcel_api_pb2.DescribeParcelV1Request, gempellm.logistic_parcel_api.v1.logistic_parcel_api_pb2.DescribeParcelV1Response]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/gempellm.logistic_parcel_api.v1.LogisticParcelApiService/DescribeParcelV1': grpclib.const.Handler(
                self.DescribeParcelV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                gempellm.logistic_parcel_api.v1.logistic_parcel_api_pb2.DescribeParcelV1Request,
                gempellm.logistic_parcel_api.v1.logistic_parcel_api_pb2.DescribeParcelV1Response,
            ),
        }


class LogisticParcelApiServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.DescribeParcelV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/gempellm.logistic_parcel_api.v1.LogisticParcelApiService/DescribeParcelV1',
            gempellm.logistic_parcel_api.v1.logistic_parcel_api_pb2.DescribeParcelV1Request,
            gempellm.logistic_parcel_api.v1.logistic_parcel_api_pb2.DescribeParcelV1Response,
        )
