// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: gempellm/logistic_parcel_api/v1/logistic_parcel_api.proto

package logistic_parcel_api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Parcel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Created *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *Parcel) Reset() {
	*x = Parcel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parcel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parcel) ProtoMessage() {}

func (x *Parcel) ProtoReflect() protoreflect.Message {
	mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parcel.ProtoReflect.Descriptor instead.
func (*Parcel) Descriptor() ([]byte, []int) {
	return file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescGZIP(), []int{0}
}

func (x *Parcel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Parcel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parcel) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

type DescribeParcelV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParcelId uint64 `protobuf:"varint,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
}

func (x *DescribeParcelV1Request) Reset() {
	*x = DescribeParcelV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeParcelV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeParcelV1Request) ProtoMessage() {}

func (x *DescribeParcelV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeParcelV1Request.ProtoReflect.Descriptor instead.
func (*DescribeParcelV1Request) Descriptor() ([]byte, []int) {
	return file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeParcelV1Request) GetParcelId() uint64 {
	if x != nil {
		return x.ParcelId
	}
	return 0
}

type DescribeParcelV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *Parcel `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DescribeParcelV1Response) Reset() {
	*x = DescribeParcelV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeParcelV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeParcelV1Response) ProtoMessage() {}

func (x *DescribeParcelV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeParcelV1Response.ProtoReflect.Descriptor instead.
func (*DescribeParcelV1Response) Descriptor() ([]byte, []int) {
	return file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeParcelV1Response) GetValue() *Parcel {
	if x != nil {
		return x.Value
	}
	return nil
}

type CreateParcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateParcelRequest) Reset() {
	*x = CreateParcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParcelRequest) ProtoMessage() {}

func (x *CreateParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParcelRequest.ProtoReflect.Descriptor instead.
func (*CreateParcelRequest) Descriptor() ([]byte, []int) {
	return file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreateParcelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateParcelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *Parcel `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CreateParcelResponse) Reset() {
	*x = CreateParcelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateParcelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParcelResponse) ProtoMessage() {}

func (x *CreateParcelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParcelResponse.ProtoReflect.Descriptor instead.
func (*CreateParcelResponse) Descriptor() ([]byte, []int) {
	return file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescGZIP(), []int{4}
}

func (x *CreateParcelResponse) GetValue() *Parcel {
	if x != nil {
		return x.Value
	}
	return nil
}

type DescribeParcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParcelId uint64 `protobuf:"varint,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
}

func (x *DescribeParcelRequest) Reset() {
	*x = DescribeParcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeParcelRequest) ProtoMessage() {}

func (x *DescribeParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeParcelRequest.ProtoReflect.Descriptor instead.
func (*DescribeParcelRequest) Descriptor() ([]byte, []int) {
	return file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeParcelRequest) GetParcelId() uint64 {
	if x != nil {
		return x.ParcelId
	}
	return 0
}

type DescribeParcelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *Parcel `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DescribeParcelResponse) Reset() {
	*x = DescribeParcelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeParcelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeParcelResponse) ProtoMessage() {}

func (x *DescribeParcelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeParcelResponse.ProtoReflect.Descriptor instead.
func (*DescribeParcelResponse) Descriptor() ([]byte, []int) {
	return file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeParcelResponse) GetValue() *Parcel {
	if x != nil {
		return x.Value
	}
	return nil
}

type ListParcelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cursor uint64 `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListParcelsRequest) Reset() {
	*x = ListParcelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListParcelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParcelsRequest) ProtoMessage() {}

func (x *ListParcelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParcelsRequest.ProtoReflect.Descriptor instead.
func (*ListParcelsRequest) Descriptor() ([]byte, []int) {
	return file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescGZIP(), []int{7}
}

func (x *ListParcelsRequest) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListParcelsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListParcelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []*Parcel `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *ListParcelsResponse) Reset() {
	*x = ListParcelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListParcelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParcelsResponse) ProtoMessage() {}

func (x *ListParcelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParcelsResponse.ProtoReflect.Descriptor instead.
func (*ListParcelsResponse) Descriptor() ([]byte, []int) {
	return file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescGZIP(), []int{8}
}

func (x *ListParcelsResponse) GetValue() []*Parcel {
	if x != nil {
		return x.Value
	}
	return nil
}

type RemoveParcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParcelId uint64 `protobuf:"varint,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
}

func (x *RemoveParcelRequest) Reset() {
	*x = RemoveParcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParcelRequest) ProtoMessage() {}

func (x *RemoveParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParcelRequest.ProtoReflect.Descriptor instead.
func (*RemoveParcelRequest) Descriptor() ([]byte, []int) {
	return file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveParcelRequest) GetParcelId() uint64 {
	if x != nil {
		return x.ParcelId
	}
	return 0
}

type RemoveParcelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RemoveParcelResponse) Reset() {
	*x = RemoveParcelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveParcelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParcelResponse) ProtoMessage() {}

func (x *RemoveParcelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParcelResponse.ProtoReflect.Descriptor instead.
func (*RemoveParcelResponse) Descriptor() ([]byte, []int) {
	return file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveParcelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto protoreflect.FileDescriptor

var file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDesc = []byte{
	0x0a, 0x39, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65,
	0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x67, 0x65, 0x6d,
	0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70,
	0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x3f, 0x0a, 0x17, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52,
	0x08, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x18, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x56, 0x31, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e,
	0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x29, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x55, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c,
	0x6d, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65,
	0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3d, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x24, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x08, 0x70, 0x61, 0x72,
	0x63, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4d,
	0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x54, 0x0a,
	0x13, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x3b, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x72,
	0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x09, 0x70, 0x61,
	0x72, 0x63, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x08, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x49, 0x64,
	0x22, 0x30, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x32, 0xc5, 0x05, 0x0a, 0x18, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x50,
	0x61, 0x72, 0x63, 0x65, 0x6c, 0x41, 0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x89, 0x01, 0x0a, 0x10, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x50, 0x61, 0x72, 0x63,
	0x65, 0x6c, 0x56, 0x31, 0x12, 0x38, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e,
	0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x50,
	0x61, 0x72, 0x63, 0x65, 0x6c, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x39,
	0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x56,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7d, 0x0a, 0x0c, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x12, 0x34, 0x2e, 0x67, 0x65,
	0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f,
	0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x35, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0xa2, 0x01, 0x0a, 0x0e, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x12, 0x36, 0x2e,
	0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x37, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d,
	0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x12, 0x17, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x72, 0x63,
	0x65, 0x6c, 0x73, 0x2f, 0x7b, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x7d, 0x12,
	0x7a, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x12, 0x33,
	0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7d, 0x0a, 0x0c, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x12, 0x34, 0x2e, 0x67, 0x65,
	0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f,
	0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x35, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x55, 0x5a, 0x53, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c,
	0x6d, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2d, 0x70, 0x61, 0x72, 0x63, 0x65,
	0x6c, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x3b, 0x6c, 0x6f,
	0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescOnce sync.Once
	file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescData = file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDesc
)

func file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescGZIP() []byte {
	file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescOnce.Do(func() {
		file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescData)
	})
	return file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDescData
}

var file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_goTypes = []interface{}{
	(*Parcel)(nil),                   // 0: gempellm.logistic_parcel_api.v1.Parcel
	(*DescribeParcelV1Request)(nil),  // 1: gempellm.logistic_parcel_api.v1.DescribeParcelV1Request
	(*DescribeParcelV1Response)(nil), // 2: gempellm.logistic_parcel_api.v1.DescribeParcelV1Response
	(*CreateParcelRequest)(nil),      // 3: gempellm.logistic_parcel_api.v1.CreateParcelRequest
	(*CreateParcelResponse)(nil),     // 4: gempellm.logistic_parcel_api.v1.CreateParcelResponse
	(*DescribeParcelRequest)(nil),    // 5: gempellm.logistic_parcel_api.v1.DescribeParcelRequest
	(*DescribeParcelResponse)(nil),   // 6: gempellm.logistic_parcel_api.v1.DescribeParcelResponse
	(*ListParcelsRequest)(nil),       // 7: gempellm.logistic_parcel_api.v1.ListParcelsRequest
	(*ListParcelsResponse)(nil),      // 8: gempellm.logistic_parcel_api.v1.ListParcelsResponse
	(*RemoveParcelRequest)(nil),      // 9: gempellm.logistic_parcel_api.v1.RemoveParcelRequest
	(*RemoveParcelResponse)(nil),     // 10: gempellm.logistic_parcel_api.v1.RemoveParcelResponse
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_depIdxs = []int32{
	11, // 0: gempellm.logistic_parcel_api.v1.Parcel.created:type_name -> google.protobuf.Timestamp
	0,  // 1: gempellm.logistic_parcel_api.v1.DescribeParcelV1Response.value:type_name -> gempellm.logistic_parcel_api.v1.Parcel
	0,  // 2: gempellm.logistic_parcel_api.v1.CreateParcelResponse.value:type_name -> gempellm.logistic_parcel_api.v1.Parcel
	0,  // 3: gempellm.logistic_parcel_api.v1.DescribeParcelResponse.value:type_name -> gempellm.logistic_parcel_api.v1.Parcel
	0,  // 4: gempellm.logistic_parcel_api.v1.ListParcelsResponse.value:type_name -> gempellm.logistic_parcel_api.v1.Parcel
	1,  // 5: gempellm.logistic_parcel_api.v1.LogisticParcelApiService.DescribeParcelV1:input_type -> gempellm.logistic_parcel_api.v1.DescribeParcelV1Request
	3,  // 6: gempellm.logistic_parcel_api.v1.LogisticParcelApiService.CreateParcel:input_type -> gempellm.logistic_parcel_api.v1.CreateParcelRequest
	5,  // 7: gempellm.logistic_parcel_api.v1.LogisticParcelApiService.DescribeParcel:input_type -> gempellm.logistic_parcel_api.v1.DescribeParcelRequest
	7,  // 8: gempellm.logistic_parcel_api.v1.LogisticParcelApiService.ListParcels:input_type -> gempellm.logistic_parcel_api.v1.ListParcelsRequest
	9,  // 9: gempellm.logistic_parcel_api.v1.LogisticParcelApiService.RemoveParcel:input_type -> gempellm.logistic_parcel_api.v1.RemoveParcelRequest
	2,  // 10: gempellm.logistic_parcel_api.v1.LogisticParcelApiService.DescribeParcelV1:output_type -> gempellm.logistic_parcel_api.v1.DescribeParcelV1Response
	4,  // 11: gempellm.logistic_parcel_api.v1.LogisticParcelApiService.CreateParcel:output_type -> gempellm.logistic_parcel_api.v1.CreateParcelResponse
	6,  // 12: gempellm.logistic_parcel_api.v1.LogisticParcelApiService.DescribeParcel:output_type -> gempellm.logistic_parcel_api.v1.DescribeParcelResponse
	8,  // 13: gempellm.logistic_parcel_api.v1.LogisticParcelApiService.ListParcels:output_type -> gempellm.logistic_parcel_api.v1.ListParcelsResponse
	10, // 14: gempellm.logistic_parcel_api.v1.LogisticParcelApiService.RemoveParcel:output_type -> gempellm.logistic_parcel_api.v1.RemoveParcelResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_init() }
func file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_init() {
	if File_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parcel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeParcelV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeParcelV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateParcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateParcelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeParcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeParcelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListParcelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListParcelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveParcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveParcelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_goTypes,
		DependencyIndexes: file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_depIdxs,
		MessageInfos:      file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_msgTypes,
	}.Build()
	File_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto = out.File
	file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_rawDesc = nil
	file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_goTypes = nil
	file_gempellm_logistic_parcel_api_v1_logistic_parcel_api_proto_depIdxs = nil
}
